//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praticis.Framework.Worker.Abstractions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueueTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueueTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Praticis.Framework.Worker.Abstractions.Resources.QueueTypeResource", typeof(QueueTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fila Padrão.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas - Diversas.
        /// </summary>
        public static string Ecac_All_Others {
            get {
                return ResourceManager.GetString("Ecac_All_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas - Processadas.
        /// </summary>
        public static string Ecac_All_Processed {
            get {
                return ResourceManager.GetString("Ecac_All_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atuais - Com Pendência.
        /// </summary>
        public static string Ecac_Current_Pending {
            get {
                return ResourceManager.GetString("Ecac_Current_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atuais - Em Processamento.
        /// </summary>
        public static string Ecac_Current_Processing {
            get {
                return ResourceManager.GetString("Ecac_Current_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atuais - Em Restituição.
        /// </summary>
        public static string Ecac_Current_Repayment {
            get {
                return ResourceManager.GetString("Ecac_Current_Repayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atuais - Aguardando Processamento.
        /// </summary>
        public static string Ecac_Current_Waiting_Process {
            get {
                return ResourceManager.GetString("Ecac_Current_Waiting_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteriores - Com Pendência.
        /// </summary>
        public static string Ecac_Previous_Pending {
            get {
                return ResourceManager.GetString("Ecac_Previous_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteriores - Em Restituição.
        /// </summary>
        public static string Ecac_Previous_Repayment {
            get {
                return ResourceManager.GetString("Ecac_Previous_Repayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteriores - Em Processamento.
        /// </summary>
        public static string Ecac_Previous_Waiting_Process {
            get {
                return ResourceManager.GetString("Ecac_Previous_Waiting_Process", resourceCulture);
            }
        }
    }
}
